controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_controller:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50
    gp7_arm_controller:
      type: "position_controllers/JointTrajectoryController"
      joints:
        - "gp7_joint_1"
        - "gp7_joint_2"
        - "gp7_joint_3"
        - "gp7_joint_4"
        - "gp7_joint_5"
        - "gp7_joint_6"
    gripper_controller:
      type: "position_controllers/GripperCommandController"
      joints:
        - "robotiq_85_left_knuckle_joint"
